In [1]:
import numpy as np
import pandas as pd

In [6]:
pd.__version__

'0.25.1'

In [8]:
a=[1,2,3,4,5]

In [9]:
a

[1, 2, 3, 4, 5]

In [10]:
len(a)

5

In [11]:
array = np.array(a)

In [15]:
array

array([1, 2, 3, 4, 5])

In [16]:
array[2]

3

In [13]:
array.size

5

In [14]:
pd.DataFrame(a, index = ['a','b','c','d','e'])

0
a  1
b  2
c  3
d  4
e  5

In [19]:
a1 = np.arange(4)
a1

array([0, 1, 2, 3])

In [21]:
a2=np.zeros((4,4), dtype=int)
a2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
a3 = np.ones((4,4))
a3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
a4 = np.full((2,3),5)
print(a4)

[[5 5 5]
 [5 5 5]]


In [25]:
a5 = np.random.normal(0,1,(3,4))
a5

array([[ 4.62435804e-01,  5.15713004e-01,  2.06133338e+00,
        -7.58229940e-01],
       [-9.07062670e-01,  9.07763817e-03,  9.60542622e-04,
         1.21617141e+00],
       [-1.05754257e+00, -7.25211751e-01,  1.41244647e+00,
        -1.95962815e+00]])

In [26]:
import matplotlib.pyplot as plt
plt.plot(a5)

In [35]:
b1 = np.array([1,2,3])
b1

array([1, 2, 3])

In [36]:
b2 = np.array([4,5,6])
b2

array([4, 5, 6])

In [40]:
b3 = np.concatenate([b1,b2])
b3

array([1, 2, 3, 4, 5, 6])

In [41]:
b3.reshape([2,3])

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
c1 = np.array([1,2,3,4])
c2 = c1.reshape([2,2])
print(c2)

[[1 2]
 [3 4]]


In [31]:
d1 = np.arange(4).reshape(1,4)
d1

array([[0, 1, 2, 3]])

In [32]:
d2 = np.arange(2,10).reshape(2,4)
d2

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [43]:
d3 = np.concatenate([d1,d2])
d3

array([[0, 1, 2, 3],
       [2, 3, 4, 5],
       [6, 7, 8, 9]])

In [52]:
ar = np.arange(8).reshape(2,4)
ar

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [53]:
gop = b1*10

In [54]:
gop

array([10, 20, 30])

In [75]:
a1 = np.arange(4).reshape(1,4)
a1

array([[0, 1, 2, 3]])

In [76]:
a2 = np.arange(4)
a2

array([0, 1, 2, 3])

In [77]:
a2 = np.arange(3,11).reshape(2,4)
a2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [78]:
a3 = np.concatenate([a1,a2], axis = 0)
a3

array([[ 0,  1,  2,  3],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [79]:
a4=np.arange(3).reshape(3,1)
a4

array([[0],
       [1],
       [2]])

In [80]:
a5 = a3+a4

In [82]:
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 9, 10, 11, 12]])

In [83]:
a6 = np.arange(16).reshape(4,4)
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
data = [1,2,3,4,5,6,7,8]
k = np.array(data)
k.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])