DAta 결합

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
list_1 =[1,2,3]

In [3]:
a=np.array(list_1)

In [4]:
a

array([1, 2, 3])

In [5]:
b=np.array([[1,2,3],[4,5,6]])

In [6]:
print(b.shape)

(2, 3)


In [7]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
lst = [
    [1,2,3]
]

In [9]:
arr = np.array(lst)

In [10]:
arr

array([[1, 2, 3]])

In [11]:
a = arr[1:, 1:]
a

array([], shape=(0, 2), dtype=int32)

In [12]:
a = arr[0:, 2:]
a = arr

In [13]:
bool_array = np.array([
    [False,True,False]
])

In [14]:
n = a[bool_array];
n

array([2])

In [15]:
a = np.array(lst)
bool_indexing = (a % 2 == 0)
print(bool_indexing)
print(a[bool_indexing])

[[False  True False]]
[2]


In [16]:
b=np.array([[1,2,3],[4,5,6]])
c = a + b
c = np.add(a,b)
print(c)

[[2 4 6]
 [5 7 9]]


In [17]:
c = a- b
c = np.subtract(a,b)
print(c)

[[ 0  0  0]
 [-3 -3 -3]]


In [18]:
c = a* b
c = np.multiply(a,b)
print(c)

[[ 1  4  9]
 [ 4 10 18]]


In [19]:
c = a/ b
c = np.multiply(a,b)
print(c)

[[ 1  4  9]
 [ 4 10 18]]


In [20]:
ar1 = np.arange(4)

In [21]:
ar1 = np.arange(4).reshape(2,2)

In [22]:
ar1

array([[0, 1],
       [2, 3]])

In [23]:
np.concatenate([ar1,ar1], axis = 0)

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [24]:
np.concatenate([ar1,ar1], axis = 1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [25]:
df1 = DataFrame({
    'A':[1,2,3],
    'B':[4,5,6]
})

In [26]:
df1

A  B
0  1  4
1  2  5
2  3  6

In [27]:
df2 = DataFrame({
    'A':[10,11],
    'B':[40,50]
})

In [28]:
df2

A   B
0  10  40
1  11  50

In [29]:
df3 = DataFrame({
    'a':[40,50,60],
    'b':[70,80,90],
    'c':[10,11,12]
})

In [30]:
df3

a   b   c
0  40  70  10
1  50  80  11
2  60  90  12

In [31]:
pd.concat([df1,df2])

A   B
0   1   4
1   2   5
2   3   6
0  10  40
1  11  50

In [32]:
pd.concat([df1,df2],axis = 1)

A  B     A     B
0  1  4  10.0  40.0
1  2  5  11.0  50.0
2  3  6   NaN   NaN

In [33]:
pd.concat([df1,df2],axis = 1,join='inner')

A  B   A   B
0  1  4  10  40
1  2  5  11  50

In [34]:
pd.concat([df1,df2],axis = 1,join='inner', keys=['ONE',"TWO"])

ONE    TWO    
    A  B   A   B
0   1  4  10  40
1   2  5  11  50

In [35]:
pd.concat([df1,df2],axis = 0,join='inner', keys=['ONE','Two'])

A   B
ONE 0   1   4
    1   2   5
    2   3   6
Two 0  10  40
    1  11  50

In [36]:
df1 = DataFrame({
    'A':[1,2,3,4],
    'B':[5,6,7,8],
    'C':[9,10,11,12]
})

In [37]:
df1

A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [38]:
df2 = DataFrame({
    'A':['a','b','c','d'],
    'D':['e','f','g','h'],
    'E':['i','j','k','l']
})

In [39]:
df2

A  D  E
0  a  e  i
1  b  f  j
2  c  g  k
3  d  h  l

In [40]:
df1.combine_first(df2)

A  B   C  D  E
0  1  5   9  e  i
1  2  6  10  f  j
2  3  7  11  g  k
3  4  8  12  h  l